"""
SECP256k1 Toy implementation for quantum circuit demonstration.

Comes from simplified Weistrass form for elliptic curves:

y² = x³ + ax + b (mod p); -> Weistrass curve
a = 0, b = 7 -> Koblitz curve SECP256k1 (simplifies computations)
y² = x³ + 7 (mod p)

This is a highly simplified version of the SECP256k1 elliptic curve operations

Parameters
----------

p : prime field modulus (a small prime for toy implementation)
p is defined as 2^(256) - 2^(32) - 2⁹ - 2⁸ - 2⁷ - 2⁶ - 2⁴ - 1
but we will use a smaller prime for simplicity, e.g., p = 17.

G: a fixed, predefined point on the curve used to start calculations
n: the order of the base point G (number of points in the subgroup generated by G)
For the toy implementation, we will use small values for G and n.

Outputs
-------

k: the private key (a random integer in [1, n-1])
Q: the public key (a point on the curve, Q = kG)

Toy Implementation
------------------

Koblitz curve SECP256k1_toy implementation:

p = 17
a = 0
b = 7
G = (12, 1)   # Base point
n = 18        # Order of the base point G

Verification for G(12,1)
------------------------

Verify that G is on the curve:

y² mod p = x³ + 7 mod p

1² mod 17 = 12³ + 7 mod 17
1 mod 17 = 1728 + 7 mod 17
1 mod 17 = 1735 mod 17

1 mod 17 = 1 mod 17 (True)

Example of key generation
-------------------------

1. Choose a private key k randomly from [1, n-1], e.g., k = 5.
2. Compute the public key Q = kG using elliptic curve point multiplication.
"""

import secrets
from typing import Optional

# Toy curve parameters (Koblitz / SECP256k1 family over F_17)
P: int = 17       # Field prime
A: int = 0        # Curve coefficient a
B: int = 7        # Curve coefficient b
G: tuple = (12, 1)  # Base point G
N: int = 18       # Order of G (|<G>| in the subgroup)

# Sentinel for the point at infinity (identity element)
INFINITY: None = None

def mod_inv(a: int, p: int) -> int:
    """Modular multiplicative inverse via Fermat's little theorem (p prime)."""
    return pow(a, p - 2, p)

def is_on_curve(point: Optional[tuple], p: int = P, b: int = B) -> bool:
    """Return True if *point* satisfies y² ≡ x³ + 7 (mod p), or is infinity."""
    if point is INFINITY:
        return True
    x, y = point
    return (y * y - x * x * x - b) % p == 0

def point_add(
    P1: Optional[tuple],
    P2: Optional[tuple],
    p: int = P,
    a: int = A,
) -> Optional[tuple]:
    """
    Elliptic-curve point addition over F_p.

    Handles:
      - Identity element (point at infinity).
      - P1 == P2  → delegates to point_double.
      - P1 == -P2 → returns INFINITY.
      - General case via the chord formula.
    """
    if P1 is INFINITY:
        return P2
    if P2 is INFINITY:
        return P1

    x1, y1 = P1
    x2, y2 = P2

    if x1 == x2:
        if y1 == y2:
            return point_double(P1, p, a)
        return INFINITY  # P1 == -P2

    m = (y2 - y1) * mod_inv(x2 - x1, p) % p
    x3 = (m * m - x1 - x2) % p
    y3 = (m * (x1 - x3) - y1) % p
    return (x3, y3)

def point_double(
    P1: Optional[tuple],
    p: int = P,
    a: int = A,
) -> Optional[tuple]:
    """
    Elliptic-curve point doubling (tangent formula).

    Uses the tangent slope  m = (3x² + a) / (2y)  over F_p.
    """
    if P1 is INFINITY:
        return INFINITY

    x1, y1 = P1
    if y1 == 0:
        return INFINITY  # tangent is vertical

    m = (3 * x1 * x1 + a) * mod_inv(2 * y1, p) % p
    x3 = (m * m - 2 * x1) % p
    y3 = (m * (x1 - x3) - y1) % p
    return (x3, y3)

def scalar_mult(
    k: int,
    point: Optional[tuple],
    p: int = P,
    a: int = A,
) -> Optional[tuple]:
    """
    Scalar multiplication  k·P  via the double-and-add algorithm.

    Complexity: O(log k) point operations.
    """
    result = INFINITY
    addend = point

    while k:
        if k & 1:
            result = point_add(result, addend, p, a)
        addend = point_double(addend, p, a)
        k >>= 1

    return result

def generate_keypair(
    n: int = N,
    g: tuple = G,
    p: int = P,
    a: int = A,
) -> tuple[int, Optional[tuple]]:
    """
    Generate a (private_key, public_key) pair.

    Returns
    -------
    k : int            — private key, chosen uniformly from [1, n-1]
    Q : tuple | None   — public key Q = k·G on the curve
    """
    k = 1 + secrets.randbelow(n - 1)  # k ∈ [1, n-1]
    Q = scalar_mult(k, g, p, a)
    return k, Q

def subgroup_points(g: tuple = G, n: int = N, p: int = P, a: int = A) -> list:
    """
    Enumerate all points in the cyclic subgroup <G> including the point at infinity.

    Useful for testing and visualisation.
    """
    points = []
    current = g
    for _ in range(n - 1):
        points.append(current)
        current = point_add(current, g, p, a)
    points.append(INFINITY)
    return points
